# C-PULSE-02/m212 probe -- dotted canonical dependency key (registry name).
# Copyright (c) 2026 Eleftherios Notas and The XIOM Authors
# SPDX-License-Identifier: MIT OR Apache-2.0
[project]
name = "m212probe_dot"

[dependencies]
xiom.rate = "0.2.0"
